### ISSUE TITLE
user_external 0.6.0 release

### ISSUE THREAD

**Issue by VicDeo** [owncloud/user_external#19]
### Reason

- Release needed for https://github.com/owncloud/user_external/pull/12 (Regression with OC 10.3.+)

**Comment by soniqsoft** [comment]
Hi,
When do you plan to release bug fix for IMAP auth on owncloud 10.3?
I applied fix in the files directly but they are reported as inconsistent which is true.
I appreciate your response very much.
Thanks!

**Comment by davitol** [comment]
Tested with IMAP and 10.3.2. RC1 and works fine

**Comment by micbar** [comment]
done
