### ISSUE TITLE
User backend OC_User_IMAP not found

### ISSUE THREAD

**Issue by peter4200** [owncloud/user_external#9]
I have just upgraded OwnCloud from version 10.2 to version 10.3 and have run the occ upgrade command without any problems.

I use IMAP to authenticate my users and after the upgrade I have a lot of “User backend OC_User_IMAP not found” errors. Nothing has changed in the config.php file.

The user_external app is enabled and I have tried to disable it and then enable it again, without any success

System information:
Fedora 30 (fully updated)
PHP 7.3.10
MariaDB 10.3.17
Dovecot 2.3.7.2

**Comment by frankreckt** [comment]
Same here. IMAP authentication using user_external works fine with 10.2 and is broken after upgrade to 10.3. “User backend OC_User_IMAP not found” occurs in the log. After going back to 10.2 everything works as expected.

System information:
Debian Jessi
PHP 7.2.23
Mysql 5.5.62

**Comment by mmattel** [comment]
@PVince81, @DeepDiver1975  have you seen that issue?

**Comment by djiti** [comment]
Same issue on Debian 9.11 (Stretch), owncloud-files version 10.3.0-1+2.1.
OC_User_IMAP was working beautifully until the owncloud-files upgrade yesterday.

**Comment by PVince81** [comment]
@micbar

**Comment by micbar** [comment]
@frankreckt Can you post the stacktrace of the error message from the logfile?

**Comment by DeepDiver1975** [comment]
Rather simple - this app uses OC::CLASSPATH which was dropping in owncloud/core in https://github.com/owncloud/core/pull/35755

https://github.com/owncloud/user_external/blob/d46ed0c9d5a2fce21b30101fe9547f5597107ddf/appinfo/app.php#L2

**Comment by lucamemini** [comment]
Any patch? :|

**Comment by lucamemini** [comment]
Ok guys, one "ugly" workaround for me is to load directly file class, like this:

```
root@server:/var/www/owncloud/apps/user_external/appinfo# head app.php
<?php
include_once('/var/www/owncloud/apps/user_external/lib/smb.php');

OC::$CLASSPATH['OC_User_IMAP']='user_external/lib/imap.php';
OC::$CLASSPATH['OC_User_SMB']='user_external/lib/smb.php';

```

**Comment by DeepDiver1975** [comment]
@lucamemini this indeed seems to be the easiest solution - mind submitting a PR so everybody can get this fix? THX

**Comment by frankreckt** [comment]
@micbar do you still need the trace from my logfile?

**Comment by micbar** [comment]
@frankreckt no, not anymore as the cause of the problem is clear.
